[build]
  base="app/"
  command = "npm run build"
  publish = "build/"


[functions]
  node_bundler = "esbuild"
  external_node_modules = ["stream/web"]


[context.production]
  environment = {VITE_ENV_TYPE="prod"}
